[build]
  publish = "."

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/css/*"
  to = "/css/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
